apiVersion: apps/v1
kind: Deployment
metadata:
  name: devices-configuration
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: devices-configuration
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
